id: P004186
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6157
  title: རྒྱུ་མཚན་ཅི་ཡིན་ཞེས་པ་དྲུག
  author: ''
  volumes:
    24aa5012638d4202899326e8fb0d531a:
      image_group_id: I1KG8407
      title: ''
      volume_number: 1
      total_pages: 186
      base_file: v001.txt
